sudo: required
language: php
php:
  - '7.2'
before_install:
- openssl aes-256-cbc -K $encrypted_326d07a343a9_key -iv $encrypted_326d07a343a9_iv
  -in php/test/Config/config.txt.enc -out php/test/Config/config.txt -d
- openssl aes-256-cbc -K $encrypted_147a1605fbb2_key -iv $encrypted_147a1605fbb2_iv
  -in php/test/Config/google.json.enc -out php/test/Config/google.json -d
- sudo pecl install grpc
- cd php
install:
- composer install
- composer clearcache
- composer update
script:
- composer test
