dist: focal
sudo: required
language: php
php:
  - '8.2'

nodejs:
  - '14.17.0'

before_install:
  - openssl aes-256-cbc -K $encrypted_a63bee63ca0e_key -iv $encrypted_a63bee63ca0e_iv
    -in php/test/Config/config.txt.enc -out php/test/Config/config.txt -d
  - openssl aes-256-cbc -K $encrypted_b047c872ff13_key -iv $encrypted_b047c872ff13_iv
    -in php/test/Config/google.json.enc -out php/test/Config/google.json -d
  - npm i -g yarn
install:
  - composer install
  - composer clearcache
  - composer update
  - cd nodejs/cli
  - yarn
  - cd ../..
script:
  - (cd php/test; phpunit --exclude-group nontravis .)
  - (cd nodejs/cli; yarn test)
